# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Dropbox\hobby\Modding\Programs\Github\My_Repos\Antipetros_Discord_Bot_new\designer_files\discord_code_builder_main_selection_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainSelectionScreen(object):
    def setupUi(self, MainSelectionScreen):
        MainSelectionScreen.setObjectName("MainSelectionScreen")
        MainSelectionScreen.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(MainSelectionScreen)
        self.gridLayout.setObjectName("gridLayout")
        self.new_cog_builder_pushButton = QtWidgets.QPushButton(MainSelectionScreen)
        self.new_cog_builder_pushButton.setObjectName("new_cog_builder_pushButton")
        self.gridLayout.addWidget(self.new_cog_builder_pushButton, 0, 0, 1, 1)
        self.new_support_builder_pushButton = QtWidgets.QPushButton(MainSelectionScreen)
        self.new_support_builder_pushButton.setObjectName("new_support_builder_pushButton")
        self.gridLayout.addWidget(self.new_support_builder_pushButton, 1, 0, 1, 1)

        self.retranslateUi(MainSelectionScreen)

    def retranslateUi(self, MainSelectionScreen):
        _translate = QtCore.QCoreApplication.translate
        MainSelectionScreen.setWindowTitle(_translate("MainSelectionScreen", "Form"))
        self.new_cog_builder_pushButton.setText(_translate("MainSelectionScreen", "New Cog Builder"))
        self.new_support_builder_pushButton.setText(_translate("MainSelectionScreen", "New Support Builder"))


import antipetros_discordbot.dev_tools_and_scripts.gui.ressources.discord_code_builder_ressources_rc
