# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Dropbox\hobby\Modding\Programs\Github\My_Repos\Antipetros_Discord_Bot_new\designer_files\discord_code_builder_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# * PyQt5 Imports --------------------------------------------------------------------------------------->
from PyQt5 import QtGui, QtCore, QtWidgets

class Ui_DiscordCodeBuilderMainWindow(object):
    def setupUi(self, DiscordCodeBuilderMainWindow):
        DiscordCodeBuilderMainWindow.setObjectName("DiscordCodeBuilderMainWindow")
        DiscordCodeBuilderMainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(DiscordCodeBuilderMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.main_stacked_widget = QtWidgets.QStackedWidget(self.centralwidget)
        self.main_stacked_widget.setObjectName("main_stacked_widget")
        self.main_hub_page = QtWidgets.QWidget()
        self.main_hub_page.setObjectName("main_hub_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.main_hub_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.main_stacked_widget.addWidget(self.main_hub_page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.main_stacked_widget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.main_stacked_widget, 0, 0, 1, 1)
        DiscordCodeBuilderMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DiscordCodeBuilderMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        DiscordCodeBuilderMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DiscordCodeBuilderMainWindow)
        self.statusbar.setObjectName("statusbar")
        DiscordCodeBuilderMainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(DiscordCodeBuilderMainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionConfigure = QtWidgets.QAction(DiscordCodeBuilderMainWindow)
        self.actionConfigure.setObjectName("actionConfigure")
        self.menuFile.addAction(self.actionQuit)
        self.menuSettings.addAction(self.actionConfigure)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(DiscordCodeBuilderMainWindow)
        QtCore.QMetaObject.connectSlotsByName(DiscordCodeBuilderMainWindow)

    def retranslateUi(self, DiscordCodeBuilderMainWindow):
        _translate = QtCore.QCoreApplication.translate
        DiscordCodeBuilderMainWindow.setWindowTitle(_translate("DiscordCodeBuilderMainWindow", "Discord Code Builder"))
        self.menuFile.setTitle(_translate("DiscordCodeBuilderMainWindow", "File"))
        self.menuEdit.setTitle(_translate("DiscordCodeBuilderMainWindow", "Edit"))
        self.menuView.setTitle(_translate("DiscordCodeBuilderMainWindow", "View"))
        self.menuSettings.setTitle(_translate("DiscordCodeBuilderMainWindow", "Settings"))
        self.actionQuit.setText(_translate("DiscordCodeBuilderMainWindow", "Quit"))
        self.actionConfigure.setText(_translate("DiscordCodeBuilderMainWindow", "Configure"))


# * Local Imports --------------------------------------------------------------------------------------->
import antipetros_discordbot.dev_tools_and_scripts.gui.ressources.discord_code_builder_ressources_rc
