# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Dropbox\hobby\Modding\Programs\Github\My_Repos\Antipetros_Discord_Bot_new\designer_files\discord_code_builder_cog_builder.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CogBuilder(object):
    def setupUi(self, CogBuilder):
        CogBuilder.setObjectName("CogBuilder")
        CogBuilder.resize(680, 698)
        CogBuilder.setMaximumSize(QtCore.QSize(680, 16777215))
        self.gridLayout_4 = QtWidgets.QGridLayout(CogBuilder)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter = QtWidgets.QSplitter(CogBuilder)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.loops_groupBox = QtWidgets.QGroupBox(self.splitter)
        self.loops_groupBox.setMinimumSize(QtCore.QSize(500, 40))
        self.loops_groupBox.setObjectName("loops_groupBox")
        self.listener_groupBox = QtWidgets.QGroupBox(self.splitter)
        self.listener_groupBox.setMinimumSize(QtCore.QSize(500, 40))
        self.listener_groupBox.setObjectName("listener_groupBox")
        self.commands_groupBox = QtWidgets.QGroupBox(self.splitter)
        self.commands_groupBox.setMinimumSize(QtCore.QSize(500, 40))
        self.commands_groupBox.setObjectName("commands_groupBox")
        self.gridLayout_4.addWidget(self.splitter, 3, 0, 1, 1)
        self.base_info_groupBox = QtWidgets.QGroupBox(CogBuilder)
        self.base_info_groupBox.setMaximumSize(QtCore.QSize(600, 16777215))
        self.base_info_groupBox.setObjectName("base_info_groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.base_info_groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.cog_name_lineEdit = QtWidgets.QLineEdit(self.base_info_groupBox)
        self.cog_name_lineEdit.setObjectName("cog_name_lineEdit")
        self.gridLayout.addWidget(self.cog_name_lineEdit, 0, 2, 1, 2)
        self.cog_category_label = QtWidgets.QLabel(self.base_info_groupBox)
        self.cog_category_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cog_category_label.setObjectName("cog_category_label")
        self.gridLayout.addWidget(self.cog_category_label, 1, 0, 1, 2)
        self.overwrite_checkBox = QtWidgets.QCheckBox(self.base_info_groupBox)
        self.overwrite_checkBox.setObjectName("overwrite_checkBox")
        self.gridLayout.addWidget(self.overwrite_checkBox, 2, 2, 1, 2)
        self.cog_category_comboBox = QtWidgets.QComboBox(self.base_info_groupBox)
        self.cog_category_comboBox.setObjectName("cog_category_comboBox")
        self.gridLayout.addWidget(self.cog_category_comboBox, 1, 2, 1, 2)
        self.cog_name_label = QtWidgets.QLabel(self.base_info_groupBox)
        self.cog_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cog_name_label.setObjectName("cog_name_label")
        self.gridLayout.addWidget(self.cog_name_label, 0, 0, 1, 2)
        self.gridLayout_4.addWidget(self.base_info_groupBox, 0, 0, 1, 2)
        self.line = QtWidgets.QFrame(CogBuilder)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 2, 0, 1, 3)
        self.extra_imports_groupBox = QtWidgets.QGroupBox(CogBuilder)
        self.extra_imports_groupBox.setMaximumSize(QtCore.QSize(600, 200))
        self.extra_imports_groupBox.setObjectName("extra_imports_groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.extra_imports_groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.add_extra_import_pushButton = QtWidgets.QPushButton(self.extra_imports_groupBox)
        self.add_extra_import_pushButton.setObjectName("add_extra_import_pushButton")
        self.gridLayout_2.addWidget(self.add_extra_import_pushButton, 1, 0, 1, 1)
        self.extra_imports_listView = QtWidgets.QListView(self.extra_imports_groupBox)
        self.extra_imports_listView.setObjectName("extra_imports_listView")
        self.gridLayout_2.addWidget(self.extra_imports_listView, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.extra_imports_groupBox, 1, 0, 1, 1)
        self.command_attr_groupBox = QtWidgets.QGroupBox(CogBuilder)
        self.command_attr_groupBox.setMinimumSize(QtCore.QSize(150, 100))
        self.command_attr_groupBox.setObjectName("command_attr_groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.command_attr_groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comattr_hidden_checkBox = QtWidgets.QCheckBox(self.command_attr_groupBox)
        self.comattr_hidden_checkBox.setObjectName("comattr_hidden_checkBox")
        self.gridLayout_3.addWidget(self.comattr_hidden_checkBox, 0, 0, 1, 1)
        self.comattr_enabled_checkBox = QtWidgets.QCheckBox(self.command_attr_groupBox)
        self.comattr_enabled_checkBox.setObjectName("comattr_enabled_checkBox")
        self.gridLayout_3.addWidget(self.comattr_enabled_checkBox, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.command_attr_groupBox, 0, 2, 2, 1)

        self.retranslateUi(CogBuilder)
        QtCore.QMetaObject.connectSlotsByName(CogBuilder)

    def retranslateUi(self, CogBuilder):
        _translate = QtCore.QCoreApplication.translate
        CogBuilder.setWindowTitle(_translate("CogBuilder", "Form"))
        self.loops_groupBox.setTitle(_translate("CogBuilder", "Loops"))
        self.listener_groupBox.setTitle(_translate("CogBuilder", "Listener"))
        self.commands_groupBox.setTitle(_translate("CogBuilder", "Commands"))
        self.base_info_groupBox.setTitle(_translate("CogBuilder", "Base Info"))
        self.cog_category_label.setText(_translate("CogBuilder", "Cog Category"))
        self.overwrite_checkBox.setText(_translate("CogBuilder", "Overwrite"))
        self.cog_name_label.setText(_translate("CogBuilder", "Cog Name: "))
        self.extra_imports_groupBox.setTitle(_translate("CogBuilder", "Extra Imports"))
        self.add_extra_import_pushButton.setText(_translate("CogBuilder", "add"))
        self.command_attr_groupBox.setTitle(_translate("CogBuilder", "Command Attributes"))
        self.comattr_hidden_checkBox.setText(_translate("CogBuilder", "Hidden"))
        self.comattr_enabled_checkBox.setText(_translate("CogBuilder", "Enabled"))


import antipetros_discordbot.dev_tools_and_scripts.gui.ressources.discord_code_builder_ressources_rc
